import type { CareProfile } from "./types";

export type BenefitTag = "pollinators" | "edible" | "water_wise" | "soil_health" | "pest_control";

export const BENEFIT_LABELS: Record<BenefitTag, string> = {
  pollinators: "Feeds pollinators",
  edible: "Grow your own food",
  water_wise: "Water-wise",
  soil_health: "Builds soil",
  pest_control: "Natural pest control",
};

export type PlantKind = "herb" | "vegetable" | "fruit" | "flower" | "houseplant" | "succulent" | "groundcover";
export type Difficulty = "easy" | "moderate" | "challenging";
export type Place = "indoor" | "outdoor";

export interface CatalogPlant {
  slug: string;
  name: string;
  scientificName: string;
  /** Lower-case names the diagnosis might call this plant. Matched on whole words. */
  aliases: string[];
  kind: PlantKind;
  places: Place[];
  difficulty: Difficulty;
  care: Omit<CareProfile, "source">;
  summary: string;
  benefits: BenefitTag[];
  /** How this plant helps beyond the pot: kept specific and modest rather than a slogan. */
  planetNote: string;
  companions: string[];
  tips: string[];
}

export const CATALOG: CatalogPlant[] = [
  {
    slug: "tomato",
    name: "Tomato",
    scientificName: "Solanum lycopersicum",
    aliases: ["tomato", "tomatoes", "cherry tomato"],
    kind: "vegetable",
    places: ["outdoor"],
    difficulty: "moderate",
    care: { light: "full_sun", waterEveryDays: 2, minTempC: 10, maxTempC: 32, frostSensitive: true },
    summary: "A sun-loving fruiting plant that rewards steady watering and regular feeding.",
    benefits: ["edible"],
    planetNote: "Home-grown tomatoes skip packaging and transport, and every plant is a chance to compost kitchen scraps back into the bed.",
    companions: ["Basil", "Marigold", "Chives"],
    tips: [
      "Water at the base in the morning; wet leaves invite fungal disease.",
      "Mulch to keep watering even, which helps prevent blossom-end rot.",
    ],
  },
  {
    slug: "basil",
    name: "Basil",
    scientificName: "Ocimum basilicum",
    aliases: ["basil", "sweet basil"],
    kind: "herb",
    places: ["indoor", "outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 2, minTempC: 10, maxTempC: 32, frostSensitive: true },
    summary: "A fast, fragrant herb that likes warmth and regular picking.",
    benefits: ["edible", "pollinators", "pest_control"],
    planetNote: "Left to flower, basil is a favourite of bees, and grown beside tomatoes it is a traditional companion.",
    companions: ["Tomato", "Pepper", "Marigold"],
    tips: [
      "Pinch the tips often to keep it bushy and delay flowering.",
      "Bring pots inside when nights drop below about 10 C.",
    ],
  },
  {
    slug: "mint",
    name: "Mint",
    scientificName: "Mentha",
    aliases: ["mint", "peppermint", "spearmint"],
    kind: "herb",
    places: ["indoor", "outdoor"],
    difficulty: "easy",
    care: { light: "bright", waterEveryDays: 3, minTempC: -10, maxTempC: 32, frostSensitive: false },
    summary: "A vigorous, hardy herb that thrives in moist soil and partial shade.",
    benefits: ["edible", "pollinators"],
    planetNote: "Its small flowers are visited by bees and hoverflies. Keep it in a pot so it does not take over.",
    companions: ["Cabbage family plants", "Peas"],
    tips: [
      "Grow it in its own pot; the runners spread quickly.",
      "Cut back hard after flowering for fresh growth.",
    ],
  },
  {
    slug: "rosemary",
    name: "Rosemary",
    scientificName: "Salvia rosmarinus",
    aliases: ["rosemary"],
    kind: "herb",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 7, minTempC: -5, maxTempC: 35, frostSensitive: false },
    summary: "A woody Mediterranean herb that prefers lean, well-drained soil and little water.",
    benefits: ["edible", "pollinators", "water_wise"],
    planetNote: "Once established it needs very little watering, and its winter and spring flowers feed early bees.",
    companions: ["Sage", "Beans", "Carrots"],
    tips: [
      "Overwatering is the usual cause of failure; let the soil dry between drinks.",
      "Prune lightly after flowering, never into old bare wood.",
    ],
  },
  {
    slug: "lavender",
    name: "Lavender",
    scientificName: "Lavandula",
    aliases: ["lavender"],
    kind: "flower",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 7, minTempC: -10, maxTempC: 35, frostSensitive: false },
    summary: "A sun-loving, drought-tolerant shrub with scented flowers.",
    benefits: ["pollinators", "water_wise"],
    planetNote: "Few garden plants are as reliably busy with bees and butterflies, and it asks for almost no watering once settled.",
    companions: ["Rosemary", "Roses", "Thyme"],
    tips: [
      "Gritty, well-drained soil matters more than feeding.",
      "Trim after flowering to keep it compact.",
    ],
  },
  {
    slug: "sunflower",
    name: "Sunflower",
    scientificName: "Helianthus annuus",
    aliases: ["sunflower", "sunflowers"],
    kind: "flower",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 3, minTempC: 5, maxTempC: 35, frostSensitive: true },
    summary: "A tall, fast annual that is easy to grow from seed.",
    benefits: ["pollinators", "edible"],
    planetNote: "The flowers feed bees, and the seed heads feed birds through autumn if you leave some standing.",
    companions: ["Cucumber", "Beans", "Squash"],
    tips: [
      "Sow where it will grow; it dislikes being transplanted.",
      "Stake tall varieties in windy spots.",
    ],
  },
  {
    slug: "marigold",
    name: "Marigold",
    scientificName: "Tagetes",
    aliases: ["marigold", "marigolds", "tagetes"],
    kind: "flower",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 3, minTempC: 5, maxTempC: 35, frostSensitive: true },
    summary: "A cheerful, tough annual that flowers for months.",
    benefits: ["pollinators", "pest_control"],
    planetNote: "A classic vegetable-bed companion: it draws hoverflies whose larvae eat aphids, and some types help deter root nematodes.",
    companions: ["Tomato", "Pepper", "Beans"],
    tips: [
      "Deadhead to keep it flowering.",
      "Tuck it along bed edges and between rows.",
    ],
  },
  {
    slug: "nasturtium",
    name: "Nasturtium",
    scientificName: "Tropaeolum majus",
    aliases: ["nasturtium", "nasturtiums"],
    kind: "flower",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 3, minTempC: 5, maxTempC: 30, frostSensitive: true },
    summary: "A sprawling annual with edible, peppery leaves and flowers.",
    benefits: ["edible", "pollinators", "pest_control"],
    planetNote: "Aphids often prefer nasturtiums to nearby crops, so it works as a trap plant that spares your vegetables.",
    companions: ["Cucumber", "Squash", "Cabbage family plants"],
    tips: [
      "Poor soil gives more flowers; skip the fertiliser.",
      "Sow directly; the large seeds are easy for children.",
    ],
  },
  {
    slug: "chives",
    name: "Chives",
    scientificName: "Allium schoenoprasum",
    aliases: ["chives", "chive"],
    kind: "herb",
    places: ["indoor", "outdoor"],
    difficulty: "easy",
    care: { light: "bright", waterEveryDays: 4, minTempC: -15, maxTempC: 30, frostSensitive: false },
    summary: "A hardy perennial herb that comes back every year.",
    benefits: ["edible", "pollinators", "pest_control"],
    planetNote: "The purple flowers are loved by bees, and the onion scent helps confuse some pests.",
    companions: ["Tomato", "Carrots", "Strawberry"],
    tips: ["Cut to about 5 cm to encourage fresh growth.", "Divide clumps every few years."],
  },
  {
    slug: "parsley",
    name: "Parsley",
    scientificName: "Petroselinum crispum",
    aliases: ["parsley"],
    kind: "herb",
    places: ["indoor", "outdoor"],
    difficulty: "easy",
    care: { light: "bright", waterEveryDays: 3, minTempC: -5, maxTempC: 30, frostSensitive: false },
    summary: "A biennial herb that likes steady moisture and cool weather.",
    benefits: ["edible", "pollinators"],
    planetNote: "It is also a food plant for swallowtail caterpillars, so plant a little extra to share.",
    companions: ["Tomato", "Asparagus"],
    tips: ["Sow in a deep pot; it grows a long taproot.", "Pick outer stems first."],
  },
  {
    slug: "coriander",
    name: "Coriander",
    scientificName: "Coriandrum sativum",
    aliases: ["coriander", "cilantro"],
    kind: "herb",
    places: ["outdoor", "indoor"],
    difficulty: "moderate",
    care: { light: "bright", waterEveryDays: 3, minTempC: -2, maxTempC: 28, frostSensitive: false },
    summary: "A quick cool-season herb that bolts to seed in heat.",
    benefits: ["edible", "pollinators", "pest_control"],
    planetNote: "When it bolts, the flowers attract hoverflies and lacewings, whose young eat aphids.",
    companions: ["Spinach", "Lettuce"],
    tips: ["Sow a little every few weeks for a steady supply.", "Give it afternoon shade in hot weather."],
  },
  {
    slug: "lettuce",
    name: "Lettuce",
    scientificName: "Lactuca sativa",
    aliases: ["lettuce", "salad leaves"],
    kind: "vegetable",
    places: ["outdoor", "indoor"],
    difficulty: "easy",
    care: { light: "bright", waterEveryDays: 2, minTempC: -2, maxTempC: 24, frostSensitive: false },
    summary: "A shallow-rooted leaf crop that wants cool weather and even moisture.",
    benefits: ["edible"],
    planetNote: "Cut-and-come-again leaves keep producing for weeks, replacing bagged salad flown or trucked in.",
    companions: ["Chives", "Radish", "Carrots"],
    tips: ["Harvest outer leaves and leave the centre growing.", "Shade it from hot afternoon sun."],
  },
  {
    slug: "kale",
    name: "Kale",
    scientificName: "Brassica oleracea",
    aliases: ["kale"],
    kind: "vegetable",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 3, minTempC: -10, maxTempC: 30, frostSensitive: false },
    summary: "A tough leafy green that keeps giving through cold weather.",
    benefits: ["edible"],
    planetNote: "It stays productive through frost, extending the season you can eat from your own garden.",
    companions: ["Nasturtium", "Chives", "Beetroot"],
    tips: ["Net against cabbage white caterpillars.", "Pick lower leaves first."],
  },
  {
    slug: "green-bean",
    name: "Green bean",
    scientificName: "Phaseolus vulgaris",
    aliases: ["bean", "beans", "green bean", "green beans", "runner bean", "french bean"],
    kind: "vegetable",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 3, minTempC: 8, maxTempC: 33, frostSensitive: true },
    summary: "A productive climber or bush plant that is quick from seed.",
    benefits: ["edible", "soil_health"],
    planetNote: "Beans host bacteria in their roots that fix nitrogen, leaving soil richer for the next crop.",
    companions: ["Marigold", "Sunflower", "Carrots"],
    tips: ["Sow after the last frost.", "Pick often; picking encourages more pods."],
  },
  {
    slug: "pea",
    name: "Pea",
    scientificName: "Pisum sativum",
    aliases: ["pea", "peas", "sweet pea"],
    kind: "vegetable",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 3, minTempC: -3, maxTempC: 24, frostSensitive: false },
    summary: "A cool-season climber that is happy in spring and autumn.",
    benefits: ["edible", "soil_health"],
    planetNote: "Like beans, peas fix nitrogen; cut the plants at the base after harvest and leave the roots in the soil.",
    companions: ["Carrots", "Mint", "Radish"],
    tips: ["Give them supports early.", "Stop when hot weather arrives; they fade above about 25 C."],
  },
  {
    slug: "chilli",
    name: "Chilli pepper",
    scientificName: "Capsicum annuum",
    aliases: ["chilli", "chili", "chilli pepper", "chili pepper", "pepper", "bell pepper", "capsicum"],
    kind: "vegetable",
    places: ["outdoor", "indoor"],
    difficulty: "moderate",
    care: { light: "full_sun", waterEveryDays: 3, minTempC: 10, maxTempC: 35, frostSensitive: true },
    summary: "A warmth-loving plant that fruits heavily on a sunny sill or in a hot bed.",
    benefits: ["edible"],
    planetNote: "One plant can give fruit for months, and dried chillies store well without refrigeration.",
    companions: ["Basil", "Marigold", "Carrots"],
    tips: ["Water when the top of the soil is dry.", "Pinch the first flowers on small plants to build a stronger frame."],
  },
  {
    slug: "cucumber",
    name: "Cucumber",
    scientificName: "Cucumis sativus",
    aliases: ["cucumber", "cucumbers"],
    kind: "vegetable",
    places: ["outdoor"],
    difficulty: "moderate",
    care: { light: "full_sun", waterEveryDays: 2, minTempC: 10, maxTempC: 34, frostSensitive: true },
    summary: "A thirsty, fast-growing climber.",
    benefits: ["edible", "pollinators"],
    planetNote: "It depends on bees for fruit, so planting flowers nearby directly improves your harvest.",
    companions: ["Nasturtium", "Sunflower", "Beans"],
    tips: ["Grow it up a trellis to save space and reduce rot.", "Water deeply and regularly."],
  },
  {
    slug: "strawberry",
    name: "Strawberry",
    scientificName: "Fragaria x ananassa",
    aliases: ["strawberry", "strawberries"],
    kind: "fruit",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 3, minTempC: -10, maxTempC: 30, frostSensitive: false },
    summary: "A hardy perennial that grows well in pots and hanging baskets. Open flowers are vulnerable to late frost.",
    benefits: ["edible", "pollinators"],
    planetNote: "Its open flowers are easy for bees to use, and the plants send out runners you can share with neighbours.",
    companions: ["Chives", "Borage", "Lettuce"],
    tips: ["Cover flowering plants on frosty nights.", "Straw or mulch keeps fruit clean and soil moist."],
  },
  {
    slug: "aloe-vera",
    name: "Aloe vera",
    scientificName: "Aloe vera",
    aliases: ["aloe", "aloe vera"],
    kind: "succulent",
    places: ["indoor", "outdoor"],
    difficulty: "easy",
    care: { light: "bright", waterEveryDays: 14, minTempC: 5, maxTempC: 38, frostSensitive: true },
    summary: "A succulent that stores water in its leaves and hates wet feet.",
    benefits: ["water_wise"],
    planetNote: "It needs water only every couple of weeks, which makes it a low-input plant for dry climates.",
    companions: ["Other succulents"],
    tips: ["Use gritty, fast-draining soil.", "Water deeply, then let it dry out fully."],
  },
  {
    slug: "snake-plant",
    name: "Snake plant",
    scientificName: "Dracaena trifasciata",
    aliases: ["snake plant", "sansevieria", "mother in law's tongue", "mother-in-law's tongue"],
    kind: "houseplant",
    places: ["indoor"],
    difficulty: "easy",
    care: { light: "low", waterEveryDays: 14, minTempC: 10, maxTempC: 32, frostSensitive: true },
    summary: "About as forgiving as a houseplant gets: low light, little water, no fuss.",
    benefits: ["water_wise"],
    planetNote: "It survives on neglect, so it is a long-lived plant that does not need replacing.",
    companions: ["Other low-light houseplants"],
    tips: ["Overwatering is the main risk. Let the soil dry completely.", "Wipe leaves occasionally to remove dust."],
  },
  {
    slug: "pothos",
    name: "Pothos",
    scientificName: "Epipremnum aureum",
    aliases: ["pothos", "devil's ivy", "devils ivy"],
    kind: "houseplant",
    places: ["indoor"],
    difficulty: "easy",
    care: { light: "medium", waterEveryDays: 7, minTempC: 12, maxTempC: 32, frostSensitive: true },
    summary: "A trailing vine that copes with most indoor light.",
    benefits: [],
    planetNote: "A cutting roots in a glass of water, so one plant can become many to share instead of buying new pots.",
    companions: ["Other tropical houseplants"],
    tips: ["Water when the top few centimetres of soil are dry.", "Trim and root the cuttings to make more."],
  },
  {
    slug: "spider-plant",
    name: "Spider plant",
    scientificName: "Chlorophytum comosum",
    aliases: ["spider plant"],
    kind: "houseplant",
    places: ["indoor"],
    difficulty: "easy",
    care: { light: "medium", waterEveryDays: 7, minTempC: 10, maxTempC: 30, frostSensitive: true },
    summary: "A tolerant houseplant that produces its own baby plants.",
    benefits: [],
    planetNote: "Its plantlets can be potted up and given away, a free way to spread green.",
    companions: ["Other tropical houseplants"],
    tips: ["Brown tips usually mean fluoride or salts in tap water; try rainwater.", "Pot up the plantlets when roots show."],
  },
  {
    slug: "peace-lily",
    name: "Peace lily",
    scientificName: "Spathiphyllum",
    aliases: ["peace lily"],
    kind: "houseplant",
    places: ["indoor"],
    difficulty: "easy",
    care: { light: "low", waterEveryDays: 5, minTempC: 12, maxTempC: 30, frostSensitive: true },
    summary: "A shade-tolerant plant that droops dramatically when thirsty.",
    benefits: [],
    planetNote: "It copes with dim rooms where little else will grow, and recovers quickly after a drink.",
    companions: ["Other shade-loving houseplants"],
    tips: ["A droop is your cue to water.", "Keep it out of direct sun."],
  },
  {
    slug: "monstera",
    name: "Monstera",
    scientificName: "Monstera deliciosa",
    aliases: ["monstera", "swiss cheese plant"],
    kind: "houseplant",
    places: ["indoor"],
    difficulty: "easy",
    care: { light: "bright", waterEveryDays: 7, minTempC: 12, maxTempC: 32, frostSensitive: true },
    summary: "A big-leaved climber that likes bright, indirect light.",
    benefits: [],
    planetNote: "Stem cuttings root easily, so a single plant can furnish a whole household.",
    companions: ["Other tropical houseplants"],
    tips: ["Give it a moss pole to climb for larger leaves.", "Let the top layer of soil dry between waterings."],
  },
  {
    slug: "jade-plant",
    name: "Jade plant",
    scientificName: "Crassula ovata",
    aliases: ["jade", "jade plant", "money plant"],
    kind: "succulent",
    places: ["indoor", "outdoor"],
    difficulty: "easy",
    care: { light: "bright", waterEveryDays: 14, minTempC: 8, maxTempC: 35, frostSensitive: true },
    summary: "A long-lived succulent with thick, water-storing leaves.",
    benefits: ["water_wise"],
    planetNote: "It stores its own water, so it thrives on infrequent watering and can live for decades.",
    companions: ["Other succulents"],
    tips: ["Give it the brightest window you have.", "Wrinkled leaves mean thirsty; soft, mushy ones mean too wet."],
  },
  {
    slug: "spekboom",
    name: "Spekboom",
    scientificName: "Portulacaria afra",
    aliases: ["spekboom", "elephant bush", "elephant's food", "portulacaria"],
    kind: "succulent",
    places: ["outdoor", "indoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 10, minTempC: 2, maxTempC: 40, frostSensitive: true },
    summary: "A tough southern African succulent shrub that shrugs off drought.",
    benefits: ["water_wise"],
    planetNote: "It is widely planted in South Africa to restore degraded land, and thrives with very little watering.",
    companions: ["Aloes", "Other succulents"],
    tips: ["Plant a cutting straight into gritty soil.", "Protect it from hard frost."],
  },
  {
    slug: "moringa",
    name: "Moringa",
    scientificName: "Moringa oleifera",
    aliases: ["moringa", "drumstick tree"],
    kind: "vegetable",
    places: ["outdoor"],
    difficulty: "moderate",
    care: { light: "full_sun", waterEveryDays: 7, minTempC: 10, maxTempC: 38, frostSensitive: true },
    summary: "A fast-growing tropical tree with edible leaves and pods that copes with dry spells.",
    benefits: ["edible", "water_wise", "pollinators"],
    planetNote: "Nutritious leaves from a drought-tolerant tree, and the flowers attract bees.",
    companions: ["Maize", "Beans"],
    tips: ["Prune the top regularly to keep it bushy and within reach.", "Protect young trees from frost."],
  },
  {
    slug: "echinacea",
    name: "Purple coneflower",
    scientificName: "Echinacea purpurea",
    aliases: ["echinacea", "coneflower", "purple coneflower"],
    kind: "flower",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 5, minTempC: -30, maxTempC: 35, frostSensitive: false },
    summary: "A sturdy perennial native to North America with long-lasting daisy-like flowers.",
    benefits: ["pollinators", "water_wise"],
    planetNote: "A magnet for bees and butterflies through summer, and the seed heads feed finches in autumn.",
    companions: ["Lavender", "Ornamental grasses"],
    tips: ["Leave the seed heads standing over winter for birds.", "Established plants tolerate dry spells."],
  },
  {
    slug: "borage",
    name: "Borage",
    scientificName: "Borago officinalis",
    aliases: ["borage"],
    kind: "flower",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 4, minTempC: 2, maxTempC: 30, frostSensitive: true },
    summary: "A hairy annual with star-shaped blue flowers that self-seeds freely.",
    benefits: ["pollinators", "edible", "pest_control"],
    planetNote: "Bees love it, and it is a traditional companion for strawberries and tomatoes.",
    companions: ["Strawberry", "Tomato", "Squash"],
    tips: ["Sow where it should grow; it has a long taproot.", "The flowers are edible in salads and drinks."],
  },
  {
    slug: "zinnia",
    name: "Zinnia",
    scientificName: "Zinnia elegans",
    aliases: ["zinnia", "zinnias"],
    kind: "flower",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "full_sun", waterEveryDays: 3, minTempC: 5, maxTempC: 35, frostSensitive: true },
    summary: "A bright, heat-loving annual that keeps flowering the more you cut it.",
    benefits: ["pollinators"],
    planetNote: "Butterflies and bees flock to the open, flat flowers through the hottest part of summer.",
    companions: ["Tomato", "Cucumber", "Sunflower"],
    tips: ["Water at the base to avoid mildew.", "Pick flowers often for more blooms."],
  },
  {
    slug: "white-clover",
    name: "White clover",
    scientificName: "Trifolium repens",
    aliases: ["clover", "white clover"],
    kind: "groundcover",
    places: ["outdoor"],
    difficulty: "easy",
    care: { light: "bright", waterEveryDays: 7, minTempC: -20, maxTempC: 35, frostSensitive: false },
    summary: "A low, tough ground cover that stays green with little water and needs almost no mowing.",
    benefits: ["pollinators", "soil_health", "water_wise"],
    planetNote: "A lawn alternative that feeds bees and fixes nitrogen, so it needs less fertiliser and less watering.",
    companions: ["Grasses", "Fruit trees"],
    tips: ["Sow over thin lawn in spring or autumn.", "Let some flower for the bees before mowing."],
  },
];

export const DEFAULT_CARE_PROFILE: CareProfile = {
  light: "bright",
  waterEveryDays: 4,
  minTempC: 5,
  maxTempC: 32,
  frostSensitive: false,
  source: "default",
};

function escapeRegex(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Finds the catalog plant a free-text name refers to, matching aliases on whole words so
 * that "peppermint" is never mistaken for "pepper". */
export function findCatalogPlant(name: string | undefined | null): CatalogPlant | undefined {
  if (!name) return undefined;
  const normalized = name.toLowerCase().replace(/[^a-z0-9' -]+/g, " ");

  let best: { plant: CatalogPlant; length: number } | undefined;
  for (const plant of CATALOG) {
    for (const alias of plant.aliases) {
      const pattern = new RegExp(`(^|[^a-z])${escapeRegex(alias)}(es|s)?($|[^a-z])`);
      if (pattern.test(normalized) && (!best || alias.length > best.length)) {
        best = { plant, length: alias.length };
      }
    }
  }
  return best?.plant;
}

export function getCatalogPlant(slug: string): CatalogPlant | undefined {
  return CATALOG.find((plant) => plant.slug === slug);
}

export function catalogCareProfile(plant: CatalogPlant): CareProfile {
  return { ...plant.care, source: "reference" };
}
